WHENEVER OSERROR EXIT FAILURE
WHENEVER SQLERROR EXIT FAILURE
SET VERIFY OFF
SET LINESIZE 200
COLUMN network_protocol FORMAT A18
COLUMN tls_version FORMAT A14
COLUMN tls_ciphersuite FORMAT A90
SELECT SYS_CONTEXT('USERENV', 'NETWORK_PROTOCOL') AS network_protocol,
       SYS_CONTEXT('USERENV', 'TLS_VERSION') AS tls_version,
       SYS_CONTEXT('USERENV', 'TLS_CIPHERSUITE') AS tls_ciphersuite
  FROM dual;
BEGIN
  IF NVL(LOWER(SYS_CONTEXT('USERENV', 'NETWORK_PROTOCOL')), 'missing') <> 'tcps'
     OR NVL(SYS_CONTEXT('USERENV', 'TLS_VERSION'), 'missing') <> '&1' THEN
    RAISE_APPLICATION_ERROR(-20001, 'Expected tcps and &1');
  END IF;
END;
/
EXIT SUCCESS
